baseURL: "https://comfy-cheesecake-ff2694.netlify.app/"
languageCode: "en-us"
title: The Watcher
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-63248109-4

buildDrafts: false
buildFuture: false
buildExpired: false

relativeURLS: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

paginate: 10
paginatePath: blog

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Learning Chess from Watching Youtube"
  author: The Watcher
  # author: ["Me", "You"] # multiple authors
  ShowPostNavLinks: true
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime:
    true
    # disableSpecial1stPost: true
  displayFullLangName: true
  comments: true
  images: ["profile.webp"]

  profileMode:
    enabled: true
    title: "Monkey See, Monkey Do" # optional default will be site title
    subtitle: "Software Engineer"
    imageUrl: "profile.webp" # optional
    imageTitle: "The Watcher" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size

    buttons:
      - { name: Blog, url: "/posts" }
      - { name: About, url: "/about" }
      - { name: Capsule Social, url: "https://capsule.social" }

  socialIcons: # optional
    - { name: "Github", url: "https://github.com/chrispanag" }
    - { name: "Twitter", url: "https://twitter.com/chrispanag" }
    - { name: "LinkedIn", url: "https://www.linkedin.com/in/chrispanag/" }
    - {
        name: "Stackoverflow",
        url: "https://stackoverflow.com/users/6141173/christos-panagiotakopoulos",
      }
    - { name: "Facebook", url: "https://facebook.com/chrispanag" }
    - { name: "Mastodon", url: "https://fosstodon.org/@chrispanag" }

taxonomies:
  category: categories
  tag: tags

menu:
  main:
    - identifier: aboutme
      name: about me
      url: /about
      weight: 5
    # - identifier: resume
    #   name: resume
    #   url: Christos_Panagiotakopoulos_-_Mid-Level_Backend_Software_Engineer.pdf
    #   weight: 6
    - identifier: blog
      name: blog
      url: /posts
      weight: 7
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
